-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
from ANIMAL_INS A, ANIMAL_OUTS B
WHERE A.ANIMAL_ID = B.ANIMAL_ID AND LEFT(A.SEX_UPON_INTAKE,6) LIKE "Intact" 
AND (LEFT(B.SEX_UPON_OUTCOME,1) LIKE 'S' OR LEFT(B.SEX_UPON_OUTCOME,1) LIKE 'N')