-- 코드를 입력하세요
SELECT F.FLAVOR
FROM FIRST_HALF AS F JOIN (SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS S FROM JULY GROUP BY FLAVOR) AS J ON  F.SHIPMENT_ID = J.SHIPMENT_ID 
ORDER BY (F.TOTAL_ORDER + J.S) DESC
LIMIT 3

# SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) AS S FROM JULY GROUP BY FLAVOR
# SELECT * FROM JULY 