-- 코드를 입력하세요
SELECT PRODUCT_CODE, (SUM(A.S) * P.PRICE) AS SALES
FROM (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS S
FROM OFFLINE_SALE
GROUP BY PRODUCT_ID) AS A JOIN PRODUCT P ON A.PRODUCT_ID = P.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC

# SELECT *, SUM(SALES_AMOUNT)
# FROM OFFLINE_SALE
# GROUP BY PRODUCT_ID
# ORDER BY PRODUCT_ID

# SELECT P.PRODUCT_ID, PRODUCT_CODE,SUM(A.S), PRICE, (SUM(A.S) * P.PRICE) AS SALES
# FROM (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS S
# FROM OFFLINE_SALE
# GROUP BY PRODUCT_ID) AS A JOIN PRODUCT P ON A.PRODUCT_ID = P.PRODUCT_ID
# GROUP BY PRODUCT_CODE
# ORDER BY SALES DESC